apiVersion: v2
name: project-origin-wallet
description: A helm chart for deploying the Project Origin Wallet
type: application
version: 0.1.0
appVersion: "0.1.0-alpha.1"

annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/licence: Apache-2.0
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/project-origin/wallet
  artifacthub.io/prerelease: "true"
  artifacthub.io/operator: "false"
